---

- name: Fix network DNS and update packages
  hosts: all
  become: true


  tasks:
    - name: Ensure DNS servers are configure
      copy:
        dest: /etc/resolv.conf
        content: |
          nameserver 8.8.8.8
          nameserver 1.1.1.1
        owner: root
        group: root
        mode: '0644'

    - name: Clean DNF cache
      command: dnf clean all

    - name: Refresh DNF metadata
      command: dnf makecache
      register: cache_output
      ignore_errors: yes

    - name: Update all packages
      dnf:
        name: "*"
        state: latest
        update_cache: true
