---

- name: Install net-tools and all dependencies
  hosts: db_server
  become: true

  tasks:

    - name: Install dependencies
      package:
        name:
          - epel-release
          - dnf-utils
        state: present

    - name: Installing net-tools
      package:
        name: net-tools
        state: present

