---


- name: Install httpd an php package
  hosts: web_server
  become: true

  vars: 
    httpd_package: httpd
    php_package: php
  tasks:

    - name: Install
      package:
        name:
          - "{{ httpd_package }}"
          - "{{ php_package }}"
        state: latest
        update_cache: yes
