---
- name: Siguran restart Nomad i Consul klastera
  hosts: nomad_servers
  become: true
  serial: 1  # KLJUČNO: Radi samo na jednom serveru u isto vreme!
  
  tasks:
    # 1. Zaustavljanje
    - name: Zaustavi Nomad
      ansible.builtin.service:
        name: nomad
        state: stopped

    - name: Zaustavi Consul
      ansible.builtin.service:
        name: consul
        state: stopped

    # Ovde možeš ubaciti taskove za update, promenu configa itd.

    # 2. Pokretanje
    - name: Pokreni Consul
      ansible.builtin.service:
        name: consul
        state: started
    
    # Čekamo da Consul stvarno postane živ pre nego što nastavimo
    - name: Proveri da li je Consul port 8500 dostupan
      ansible.builtin.wait_for:
        port: 8500
        delay: 5
        timeout: 60

    - name: Pokreni Nomad
      ansible.builtin.service:
        name: nomad
        state: started

    - name: Proveri da li je Nomad port 4646 dostupan
      ansible.builtin.wait_for:
        port: 4646
        delay: 5
        timeout: 60